export const ACTION = {
  LOAD_PROFILE: 'LOAD_PROFILE',
  LOAD_PROFILE_COMPLETED: 'LOAD_PROFILE_COMPLETED',

  LOAD_FAVORITES: 'LOAD_FAVORITES',
  LOAD_FAVORITES_COMPLETED: 'LOAD_FAVORITES_COMPLETED',

  LOAD_CHARTS: 'LOAD_CHARTS',
  LOAD_CHARTS_COMPLETED: 'LOAD_CHARTS_COMPLETED',

  LOAD_TRACK: 'LOAD_TRACK',
  LOAD_TRACK_COMPLETED: 'LOAD_TRACK_COMPLETED',

  PLAY: 'PLAY',
  PAUSE: 'PAUSE',

  SKIP_FORWARD: 'SKIP_FORWARD',
  SKIP_BACKWARD: 'SKIP_BACKWARD',

  UPDATE_STATE: 'UPDATE_STATE',

  LOAD_SEARCH: 'LOAD_SEARCH',
  LOAD_SEARCH_COMPLETED: 'LOAD_SEARCH_COMPLETED',

  LOAD_ARTIST: 'LOAD_ARTIST',
  LOAD_ARTIST_COMPLETED: 'LOAD_ARTIST_COMPLETED',

  VERIFY_USER: 'VERIFY_USER',
  VERIFY_USER_COMPLETED: 'VERIFY_USER_COMPLETED',

  LOAD_GENRES: 'LOAD_GENRES',
  LOAD_GENRES_COMPLETED: 'LOAD_GENRES_COMPLETED',

  SEEK: 'SEEK',
  SHUFFLE: 'SHUFFLE',

  LOAD_PLAYLISTS: 'LOAD_PLAYLISTS',
  LOAD_PLAYLISTS_COMPLETED: 'LOAD_PLAYLISTS_COMPLETED',

  LOAD_PLAYLIST: 'LOAD_PLAYLIST',
  LOAD_PLAYLIST_COMPLETED: 'LOAD_PLAYLIST_COMPLETED'
};
