export const ACTION = {
  LOAD_PROFILE: 'LOAD_PROFILE',
  LOAD_PROFILE_COMPLETED: 'LOAD_PROFILE_COMPLETED',

  LOAD_FAVORITES: 'LOAD_FAVORITES',
  LOAD_FAVORITES_COMPLETED: 'LOAD_FAVORITES_COMPLETED',

  LOAD_TRACKS_FAVORITES: 'LOAD_TRACKS_FAVORITES',
  LOAD_TRACKS_FAVORITES_COMPLETED: 'LOAD_TRACKS_FAVORITES_COMPLETED'
};
